In [1]:
import pandas as pd
import numpy as np

In [2]:
csv_2019 = "2019 june trip data.csv"
csv_2020 = "2020 june trip data.csv"

bike_trip_2019 = pd.read_csv(csv_2019)
bike_trip_2020 = pd.read_csv(csv_2020)

In [5]:
bike_2019_df = bike_trip_2019
bike_2019_df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,316,2019-06-01 00:05:55.7210,2019-06-01 00:11:11.9940,3187,Warren St,40.721124,-74.038051,3199,Newport Pkwy,40.728745,-74.032108,29677,Subscriber,1993,1
1,280,2019-06-01 00:08:09.0920,2019-06-01 00:12:50.0730,3185,City Hall,40.717732,-74.043845,3267,Morris Canal,40.712419,-74.038526,29571,Subscriber,1984,1
2,2162,2019-06-01 00:13:11.8800,2019-06-01 00:49:14.3640,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,26208,Customer,1969,0
3,2184,2019-06-01 00:13:30.1110,2019-06-01 00:49:54.2250,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,29487,Customer,1969,0
4,139,2019-06-01 00:13:31.8520,2019-06-01 00:15:51.7880,3207,Oakland Ave,40.737604,-74.052478,3207,Oakland Ave,40.737604,-74.052478,29592,Subscriber,1994,1

In [6]:
bike_2020_df = bike_trip_2020
bike_2020_df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,122,2020-06-01 00:02:21.7500,2020-06-01 00:04:24.3250,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,3639,Harborside,40.719252,-74.034234,42489,Subscriber,1987,1
1,1282,2020-06-01 00:12:27.1090,2020-06-01 00:33:50.0540,3198,Heights Elevator,40.748716,-74.040443,3276,Marin Light Rail,40.714584,-74.042817,42183,Subscriber,1988,1
2,186,2020-06-01 01:19:59.2090,2020-06-01 01:23:05.8930,3275,Columbus Drive,40.718355,-74.038914,3681,Grand St,40.715178,-74.037683,42140,Subscriber,1987,1
3,131,2020-06-01 01:26:42.2050,2020-06-01 01:28:53.8040,3267,Morris Canal,40.712419,-74.038526,3681,Grand St,40.715178,-74.037683,42120,Subscriber,1987,1
4,266,2020-06-01 01:27:33.7090,2020-06-01 01:32:00.1890,3639,Harborside,40.719252,-74.034234,3186,Grove St PATH,40.719586,-74.043117,42437,Subscriber,1972,2

In [7]:
del bike_2019_df['usertype']
del bike_2020_df['usertype']

In [9]:
bike_2019_df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,birth year,gender
0,316,2019-06-01 00:05:55.7210,2019-06-01 00:11:11.9940,3187,Warren St,40.721124,-74.038051,3199,Newport Pkwy,40.728745,-74.032108,29677,1993,1
1,280,2019-06-01 00:08:09.0920,2019-06-01 00:12:50.0730,3185,City Hall,40.717732,-74.043845,3267,Morris Canal,40.712419,-74.038526,29571,1984,1
2,2162,2019-06-01 00:13:11.8800,2019-06-01 00:49:14.3640,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,26208,1969,0
3,2184,2019-06-01 00:13:30.1110,2019-06-01 00:49:54.2250,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,29487,1969,0
4,139,2019-06-01 00:13:31.8520,2019-06-01 00:15:51.7880,3207,Oakland Ave,40.737604,-74.052478,3207,Oakland Ave,40.737604,-74.052478,29592,1994,1

In [10]:
bike_2020_df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,birth year,gender
0,122,2020-06-01 00:02:21.7500,2020-06-01 00:04:24.3250,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,3639,Harborside,40.719252,-74.034234,42489,1987,1
1,1282,2020-06-01 00:12:27.1090,2020-06-01 00:33:50.0540,3198,Heights Elevator,40.748716,-74.040443,3276,Marin Light Rail,40.714584,-74.042817,42183,1988,1
2,186,2020-06-01 01:19:59.2090,2020-06-01 01:23:05.8930,3275,Columbus Drive,40.718355,-74.038914,3681,Grand St,40.715178,-74.037683,42140,1987,1
3,131,2020-06-01 01:26:42.2050,2020-06-01 01:28:53.8040,3267,Morris Canal,40.712419,-74.038526,3681,Grand St,40.715178,-74.037683,42120,1987,1
4,266,2020-06-01 01:27:33.7090,2020-06-01 01:32:00.1890,3639,Harborside,40.719252,-74.034234,3186,Grove St PATH,40.719586,-74.043117,42437,1972,2

In [11]:
bike_2019_df.dtypes

tripduration                 int64
starttime                   object
stoptime                    object
start station id             int64
start station name          object
start station latitude     float64
start station longitude    float64
end station id               int64
end station name            object
end station latitude       float64
end station longitude      float64
bikeid                       int64
birth year                   int64
gender                       int64
dtype: object

In [12]:
bike_2020_df.dtypes

tripduration                 int64
starttime                   object
stoptime                    object
start station id             int64
start station name          object
start station latitude     float64
start station longitude    float64
end station id               int64
end station name            object
end station latitude       float64
end station longitude      float64
bikeid                       int64
birth year                   int64
gender                       int64
dtype: object

In [13]:
bike_2019_df['gender'] = bike_2019_df['gender'].astype(str)
bike_2020_df['gender'] = bike_2020_df['gender'].astype(str)

In [14]:
checking_gender_2019 = bike_2019_df['gender']
male_2019 = checking_gender_2019.replace('1', 'Male')
female_2019 = male_2019.replace('2', 'Female')
unknown_2019 = female_2019.replace('0', 'Unknown')
bike_2019_df['gender'] = unknown_2019
bike_2019_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,birth year,gender
0,316,2019-06-01 00:05:55.7210,2019-06-01 00:11:11.9940,3187,Warren St,40.721124,-74.038051,3199,Newport Pkwy,40.728745,-74.032108,29677,1993,Male
1,280,2019-06-01 00:08:09.0920,2019-06-01 00:12:50.0730,3185,City Hall,40.717732,-74.043845,3267,Morris Canal,40.712419,-74.038526,29571,1984,Male
2,2162,2019-06-01 00:13:11.8800,2019-06-01 00:49:14.3640,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,26208,1969,Unknown
3,2184,2019-06-01 00:13:30.1110,2019-06-01 00:49:54.2250,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,29487,1969,Unknown
4,139,2019-06-01 00:13:31.8520,2019-06-01 00:15:51.7880,3207,Oakland Ave,40.737604,-74.052478,3207,Oakland Ave,40.737604,-74.052478,29592,1994,Male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39425,639,2019-06-30 23:38:29.5450,2019-06-30 23:49:09.2110,3677,Glenwood Ave,40.727551,-74.071061,3191,Union St,40.718211,-74.083639,29197,1986,Male
39426,643,2019-06-30 23:38:34.9100,2019-06-30 23:49:17.9690,3677,Glenwood Ave,40.727551,-74.071061,3191,Union St,40.718211,-74.083639,26262,1990,Female
39427,418,2019-06-30 23:42:30.9400,2019-06-30 23:49:29.5360,3679,Bergen Ave,40.722104,-74.071455,3191,Union St,40.718211,-74.083639,29241,1979,Male
39428,2529,2019-06-30 23:46:17.5700,2019-07-01 00:28:27.1710,3185,City Hall,40.717732,-74.043845,3213,Van Vorst Park,40.718489,-74.047727,26254,1982,Male
39429,831,2019-06-30 23:49:01.6830,2019-07-01 00:02:53.1150,3210,Pershing Field,40.742677,-74.051789,3186,Grove St PATH,40.719586,-74.043117,29551,1988,Male

In [15]:
checking_gender_2020 = bike_2020_df['gender']
male_2020 = checking_gender_2020.replace('1', 'Male')
female_2020 = male_2020.replace('2', 'Female')
unknown_2020 = female_2020.replace('0', 'Unknown')
bike_2020_df['gender'] = unknown_2020
bike_2020_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,birth year,gender
0,122,2020-06-01 00:02:21.7500,2020-06-01 00:04:24.3250,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,3639,Harborside,40.719252,-74.034234,42489,1987,Male
1,1282,2020-06-01 00:12:27.1090,2020-06-01 00:33:50.0540,3198,Heights Elevator,40.748716,-74.040443,3276,Marin Light Rail,40.714584,-74.042817,42183,1988,Male
2,186,2020-06-01 01:19:59.2090,2020-06-01 01:23:05.8930,3275,Columbus Drive,40.718355,-74.038914,3681,Grand St,40.715178,-74.037683,42140,1987,Male
3,131,2020-06-01 01:26:42.2050,2020-06-01 01:28:53.8040,3267,Morris Canal,40.712419,-74.038526,3681,Grand St,40.715178,-74.037683,42120,1987,Male
4,266,2020-06-01 01:27:33.7090,2020-06-01 01:32:00.1890,3639,Harborside,40.719252,-74.034234,3186,Grove St PATH,40.719586,-74.043117,42437,1972,Female
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36916,2828,2020-06-30 23:53:19.7380,2020-07-01 00:40:28.5760,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,18351,1969,Unknown
36917,2729,2020-06-30 23:54:44.0100,2020-07-01 00:40:13.6470,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,44401,1969,Unknown
36918,2788,2020-06-30 23:54:52.1920,2020-07-01 00:41:20.6500,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,42334,1969,Unknown
36919,2702,2020-06-30 23:56:14.6650,2020-07-01 00:41:16.7820,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,42463,1969,Unknown
36920,2649,2020-06-30 23:57:46.1490,2020-07-01 00:41:55.5060,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,42468,1998,Female

In [16]:
current_year = 2021

birth_year_2019 = bike_2019_df['birth year']
age = current_year - birth_year_2019
bike_2019_df['age'] = age

birth_year_2020 = bike_2020_df['birth year']
age = current_year - birth_year_2020
bike_2020_df['age'] = age

In [18]:
bike_2019_df_organized = bike_2019_df[["bikeid",
                                       "gender",
                                       "birth year",
                                       "age",
                                       "tripduration",
                                       "start station id",
                                       "start station name",
                                       "start station latitude",
                                       "start station longitude",
                                       "starttime",
                                       "end station id",
                                       "end station name", 
                                       "end station latitude",
                                       "end station longitude",
                                       "stoptime"]]

bike_2020_df_organized = bike_2020_df[["bikeid",
                                       "gender",
                                       "birth year",
                                       "age",
                                       "tripduration",
                                       "start station id",
                                       "start station name",
                                       "start station latitude",
                                       "start station longitude",
                                       "starttime",
                                       "end station id",
                                       "end station name", 
                                       "end station latitude",
                                       "end station longitude",
                                       "stoptime"]]

bike_2019_df_organized.head()

,bikeid,gender,birth year,age,tripduration,start station id,start station name,start station latitude,start station longitude,starttime,end station id,end station name,end station latitude,end station longitude,stoptime
0,29677,Male,1993,28,316,3187,Warren St,40.721124,-74.038051,2019-06-01 00:05:55.7210,3199,Newport Pkwy,40.728745,-74.032108,2019-06-01 00:11:11.9940
1,29571,Male,1984,37,280,3185,City Hall,40.717732,-74.043845,2019-06-01 00:08:09.0920,3267,Morris Canal,40.712419,-74.038526,2019-06-01 00:12:50.0730
2,26208,Unknown,1969,52,2162,3199,Newport Pkwy,40.728745,-74.032108,2019-06-01 00:13:11.8800,3199,Newport Pkwy,40.728745,-74.032108,2019-06-01 00:49:14.3640
3,29487,Unknown,1969,52,2184,3199,Newport Pkwy,40.728745,-74.032108,2019-06-01 00:13:30.1110,3199,Newport Pkwy,40.728745,-74.032108,2019-06-01 00:49:54.2250
4,29592,Male,1994,27,139,3207,Oakland Ave,40.737604,-74.052478,2019-06-01 00:13:31.8520,3207,Oakland Ave,40.737604,-74.052478,2019-06-01 00:15:51.7880

In [19]:
bike_2020_df_organized.head()

,bikeid,gender,birth year,age,tripduration,start station id,start station name,start station latitude,start station longitude,starttime,end station id,end station name,end station latitude,end station longitude,stoptime
0,42489,Male,1987,34,122,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,2020-06-01 00:02:21.7500,3639,Harborside,40.719252,-74.034234,2020-06-01 00:04:24.3250
1,42183,Male,1988,33,1282,3198,Heights Elevator,40.748716,-74.040443,2020-06-01 00:12:27.1090,3276,Marin Light Rail,40.714584,-74.042817,2020-06-01 00:33:50.0540
2,42140,Male,1987,34,186,3275,Columbus Drive,40.718355,-74.038914,2020-06-01 01:19:59.2090,3681,Grand St,40.715178,-74.037683,2020-06-01 01:23:05.8930
3,42120,Male,1987,34,131,3267,Morris Canal,40.712419,-74.038526,2020-06-01 01:26:42.2050,3681,Grand St,40.715178,-74.037683,2020-06-01 01:28:53.8040
4,42437,Female,1972,49,266,3639,Harborside,40.719252,-74.034234,2020-06-01 01:27:33.7090,3186,Grove St PATH,40.719586,-74.043117,2020-06-01 01:32:00.1890

In [20]:
bike_2019_renamed_df = bike_2019_df_organized.rename(columns={"bikeid":"Bike ID", 
                                                              "gender":"Gender",
                                                              "birth year":"Birth Year",
                                                              "age":"Age",
                                                              "tripduration":"Trip Duration",
                                                              "start station id":"Start Station ID",
                                                              "start station name":"Start Station Name",
                                                              "start station latitude":"Start Station Latitude",
                                                              "start station longitude":"Start Station Longitude",
                                                              "starttime":"Start Time",
                                                              "end station id":"End Station ID",
                                                              "end station name":"End Station Name",
                                                              "end station latitude":"End Station Latitude",
                                                              "end station longitude":"End Station Longitude",
                                                              "stoptime":"Stop Time"})

bike_2020_renamed_df = bike_2020_df_organized.rename(columns={"bikeid":"Bike ID", 
                                                              "gender":"Gender",
                                                              "birth year":"Birth Year",
                                                              "age":"Age",
                                                              "tripduration":"Trip Duration",
                                                              "start station id":"Start Station ID",
                                                              "start station name":"Start Station Name",
                                                              "start station latitude":"Start Station Latitude",
                                                              "start station longitude":"Start Station Longitude",
                                                              "starttime":"Start Time",
                                                              "end station id":"End Station ID",
                                                              "end station name":"End Station Name",
                                                              "end station latitude":"End Station Latitude",
                                                              "end station longitude":"End Station Longitude",
                                                              "stoptime":"Stop Time"})



bike_2019_renamed_df

,Bike ID,Gender,Birth Year,Age,Trip Duration,Start Station ID,Start Station Name,Start Station Latitude,Start Station Longitude,Start Time,End Station ID,End Station Name,End Station Latitude,End Station Longitude,Stop Time
0,29677,Male,1993,28,316,3187,Warren St,40.721124,-74.038051,2019-06-01 00:05:55.7210,3199,Newport Pkwy,40.728745,-74.032108,2019-06-01 00:11:11.9940
1,29571,Male,1984,37,280,3185,City Hall,40.717732,-74.043845,2019-06-01 00:08:09.0920,3267,Morris Canal,40.712419,-74.038526,2019-06-01 00:12:50.0730
2,26208,Unknown,1969,52,2162,3199,Newport Pkwy,40.728745,-74.032108,2019-06-01 00:13:11.8800,3199,Newport Pkwy,40.728745,-74.032108,2019-06-01 00:49:14.3640
3,29487,Unknown,1969,52,2184,3199,Newport Pkwy,40.728745,-74.032108,2019-06-01 00:13:30.1110,3199,Newport Pkwy,40.728745,-74.032108,2019-06-01 00:49:54.2250
4,29592,Male,1994,27,139,3207,Oakland Ave,40.737604,-74.052478,2019-06-01 00:13:31.8520,3207,Oakland Ave,40.737604,-74.052478,2019-06-01 00:15:51.7880
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39425,29197,Male,1986,35,639,3677,Glenwood Ave,40.727551,-74.071061,2019-06-30 23:38:29.5450,3191,Union St,40.718211,-74.083639,2019-06-30 23:49:09.2110
39426,26262,Female,1990,31,643,3677,Glenwood Ave,40.727551,-74.071061,2019-06-30 23:38:34.9100,3191,Union St,40.718211,-74.083639,2019-06-30 23:49:17.9690
39427,29241,Male,1979,42,418,3679,Bergen Ave,40.722104,-74.071455,2019-06-30 23:42:30.9400,3191,Union St,40.718211,-74.083639,2019-06-30 23:49:29.5360
39428,26254,Male,1982,39,2529,3185,City Hall,40.717732,-74.043845,2019-06-30 23:46:17.5700,3213,Van Vorst Park,40.718489,-74.047727,2019-07-01 00:28:27.1710
39429,29551,Male,1988,33,831,3210,Pershing Field,40.742677,-74.051789,2019-06-30 23:49:01.6830,3186,Grove St PATH,40.719586,-74.043117,2019-07-01 00:02:53.1150

In [21]:
bike_2020_renamed_df

,Bike ID,Gender,Birth Year,Age,Trip Duration,Start Station ID,Start Station Name,Start Station Latitude,Start Station Longitude,Start Time,End Station ID,End Station Name,End Station Latitude,End Station Longitude,Stop Time
0,42489,Male,1987,34,122,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,2020-06-01 00:02:21.7500,3639,Harborside,40.719252,-74.034234,2020-06-01 00:04:24.3250
1,42183,Male,1988,33,1282,3198,Heights Elevator,40.748716,-74.040443,2020-06-01 00:12:27.1090,3276,Marin Light Rail,40.714584,-74.042817,2020-06-01 00:33:50.0540
2,42140,Male,1987,34,186,3275,Columbus Drive,40.718355,-74.038914,2020-06-01 01:19:59.2090,3681,Grand St,40.715178,-74.037683,2020-06-01 01:23:05.8930
3,42120,Male,1987,34,131,3267,Morris Canal,40.712419,-74.038526,2020-06-01 01:26:42.2050,3681,Grand St,40.715178,-74.037683,2020-06-01 01:28:53.8040
4,42437,Female,1972,49,266,3639,Harborside,40.719252,-74.034234,2020-06-01 01:27:33.7090,3186,Grove St PATH,40.719586,-74.043117,2020-06-01 01:32:00.1890
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36916,18351,Unknown,1969,52,2828,3199,Newport Pkwy,40.728745,-74.032108,2020-06-30 23:53:19.7380,3199,Newport Pkwy,40.728745,-74.032108,2020-07-01 00:40:28.5760
36917,44401,Unknown,1969,52,2729,3199,Newport Pkwy,40.728745,-74.032108,2020-06-30 23:54:44.0100,3199,Newport Pkwy,40.728745,-74.032108,2020-07-01 00:40:13.6470
36918,42334,Unknown,1969,52,2788,3199,Newport Pkwy,40.728745,-74.032108,2020-06-30 23:54:52.1920,3199,Newport Pkwy,40.728745,-74.032108,2020-07-01 00:41:20.6500
36919,42463,Unknown,1969,52,2702,3199,Newport Pkwy,40.728745,-74.032108,2020-06-30 23:56:14.6650,3199,Newport Pkwy,40.728745,-74.032108,2020-07-01 00:41:16.7820
36920,42468,Female,1998,23,2649,3199,Newport Pkwy,40.728745,-74.032108,2020-06-30 23:57:46.1490,3199,Newport Pkwy,40.728745,-74.032108,2020-07-01 00:41:55.5060

In [22]:
bike_2019_renamed_df.to_csv("2019_june_citibike_tripdata_cleaned.csv", index=False, header=True)
bike_2020_renamed_df.to_csv("2020_june_citibike_tripdata_cleaned.csv", index=False, header=True)