In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import os

In [4]:
joining_january = os.path.join("january 2020 bike data.csv")
joining_february = os.path.join("february 2020 bike data.csv")
joining_march = os.path.join("march 2020 bike data.csv")
joining_april = os.path.join("april 2020 bike data.csv")
joining_may = os.path.join("may 2020 bike data.csv")
joining_june = os.path.join("june 2020 bike data.csv")
joining_july = os.path.join("july 2020 bike data.csv")
joining_august = os.path.join("august 2020 bike data.csv")
joining_september = os.path.join("september 2020 bike data.csv")
joining_october = os.path.join("october 2020 bike data.csv")
joining_november = os.path.join("november 2020 bike data.csv")
joining_december = os.path.join("december 2020 bike data.csv")


january = pd.read_csv(joining_january)
february = pd.read_csv(joining_february)
march = pd.read_csv(joining_march)
april = pd.read_csv(joining_april)
may = pd.read_csv(joining_may)
june = pd.read_csv(joining_june)
july = pd.read_csv(joining_july)
august = pd.read_csv(joining_august)
september = pd.read_csv(joining_september)
october = pd.read_csv(joining_october)
november = pd.read_csv(joining_november)
december = pd.read_csv(joining_december)

In [5]:
january

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,226,2020-01-01 00:04:50.1920,2020-01-01 00:08:37.0370,3186,Grove St PATH,40.719586,-74.043117,3211,Newark Ave,40.721525,-74.046305,29444,Subscriber,1984,2
1,377,2020-01-01 00:16:01.6700,2020-01-01 00:22:19.0800,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,26305,Subscriber,1989,2
2,288,2020-01-01 00:17:33.8770,2020-01-01 00:22:22.4420,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,29268,Customer,1989,1
3,435,2020-01-01 00:32:05.9020,2020-01-01 00:39:21.0660,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,29278,Customer,1969,0
4,231,2020-01-01 00:46:19.6780,2020-01-01 00:50:11.3440,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,-74.042817,29276,Subscriber,1983,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26015,544,2020-01-31 23:29:29.3910,2020-01-31 23:38:33.6910,3213,Van Vorst Park,40.718489,-74.047727,3194,McGinley Square,40.725340,-74.067622,29659,Subscriber,1989,1
26016,122,2020-01-31 23:30:59.3670,2020-01-31 23:33:01.6870,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,3639,Harborside,40.719252,-74.034234,42361,Subscriber,1991,1
26017,201,2020-01-31 23:42:34.8460,2020-01-31 23:45:55.8780,3273,Manila & 1st,40.721651,-74.042884,3209,Brunswick St,40.724176,-74.050656,42368,Subscriber,1988,1
26018,300,2020-01-31 23:45:00.6800,2020-01-31 23:50:00.8740,3185,City Hall,40.717732,-74.043845,3267,Morris Canal,40.712419,-74.038526,42257,Subscriber,1981,2
26019,721,2020-01-31 23:48:35.1700,2020-02-01 00:00:36.4060,3206,Hilltop,40.731169,-74.057574,3202,Newport PATH,40.727224,-74.033759,29302,Customer,1998,1

In [6]:
february

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1404,2020-02-01 00:00:05.9460,2020-02-01 00:23:30.7240,316,Fulton St & William St,40.709560,-74.006536,481,S 3 St & Bedford Ave,40.712605,-73.962644,28874,Customer,1995,1
1,1301,2020-02-01 00:00:06.2230,2020-02-01 00:21:48.0580,237,E 11 St & 2 Ave,40.730473,-73.986724,539,Metropolitan Ave & Bedford Ave,40.715348,-73.960241,32588,Subscriber,1991,1
2,474,2020-02-01 00:00:15.7210,2020-02-01 00:08:10.3440,528,2 Ave & E 31 St,40.742909,-73.977061,3785,W 42 St & 6 Ave,40.754920,-73.984550,41013,Subscriber,1994,1
3,487,2020-02-01 00:00:21.0520,2020-02-01 00:08:28.7520,380,W 4 St & 7 Ave S,40.734011,-74.002939,3263,Cooper Square & Astor Pl,40.729515,-73.990753,27581,Subscriber,1973,2
4,619,2020-02-01 00:00:27.4000,2020-02-01 00:10:47.0640,472,E 32 St & Park Ave,40.745712,-73.981948,237,E 11 St & 2 Ave,40.730473,-73.986724,29062,Subscriber,1994,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1146825,203,2020-02-29 23:58:48.0230,2020-03-01 00:02:11.6640,3737,Stanton St & Norfolk St,40.720747,-73.986274,317,E 6 St & Avenue B,40.724537,-73.981854,39094,Subscriber,1993,2
1146826,357,2020-02-29 23:58:52.5640,2020-03-01 00:04:50.5370,546,E 30 St & Park Ave S,40.744449,-73.983035,3463,E 16 St & Irving Pl,40.735367,-73.987974,40722,Subscriber,1966,2
1146827,169,2020-02-29 23:58:54.5820,2020-03-01 00:01:43.7770,3043,Lewis Ave & Decatur St,40.681460,-73.934903,3052,Lewis Ave & Madison St,40.686312,-73.935775,28696,Subscriber,1994,1
1146828,738,2020-02-29 23:58:58.8110,2020-03-01 00:11:17.7390,3255,8 Ave & W 31 St,40.750585,-73.994685,497,E 17 St & Broadway,40.737050,-73.990093,19975,Subscriber,1999,1
1146829,960,2020-02-29 23:59:35.6070,2020-03-01 00:15:35.6490,379,W 31 St & 7 Ave,40.749156,-73.991600,3744,1 Ave & E 5 St,40.725864,-73.986389,38651,Subscriber,1990,1

In [7]:
march

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1589,2020-03-01 00:00:03.6400,2020-03-01 00:26:32.9860,224,Spruce St & Nassau St,40.711464,-74.005524,3574,Prospect Pl & Underhill Ave,40.676969,-73.965790,16214,Subscriber,1980,1
1,389,2020-03-01 00:00:16.7560,2020-03-01 00:06:46.0620,293,Lafayette St & E 8 St,40.730207,-73.991026,223,W 13 St & 7 Ave,40.737815,-73.999947,29994,Subscriber,1991,2
2,614,2020-03-01 00:00:20.0580,2020-03-01 00:10:34.2200,379,W 31 St & 7 Ave,40.749156,-73.991600,515,W 43 St & 10 Ave,40.760094,-73.994618,39853,Subscriber,1991,1
3,597,2020-03-01 00:00:24.3510,2020-03-01 00:10:22.3390,3739,Perry St & Greenwich Ave,40.735918,-74.000939,325,E 19 St & 3 Ave,40.736245,-73.984738,42608,Subscriber,1989,1
4,1920,2020-03-01 00:00:26.1120,2020-03-01 00:32:26.2680,236,St Marks Pl & 2 Ave,40.728419,-73.987140,3124,46 Ave & 5 St,40.747310,-73.954510,36288,Subscriber,1993,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1068452,137,2020-03-31 23:56:06.0490,2020-03-31 23:58:23.3880,422,W 59 St & 10 Ave,40.770513,-73.988038,3356,Amsterdam Ave & W 66 St,40.774667,-73.984706,18851,Subscriber,1989,2
1068453,1548,2020-03-31 23:57:27.6850,2020-04-01 00:23:16.4110,523,W 38 St & 8 Ave,40.754666,-73.991382,442,W 27 St & 7 Ave,40.746647,-73.993915,36539,Subscriber,1993,1
1068454,308,2020-03-31 23:58:00.2690,2020-04-01 00:03:08.9500,528,2 Ave & E 31 St,40.742909,-73.977061,487,E 20 St & FDR Drive,40.733143,-73.975739,43023,Subscriber,1982,1
1068455,872,2020-03-31 23:58:42.9010,2020-04-01 00:13:15.5860,3043,Lewis Ave & Decatur St,40.681460,-73.934903,3755,DeKalb Ave & Franklin Ave,40.690648,-73.957462,43073,Customer,1990,1
1068456,306,2020-03-31 23:59:17.2580,2020-04-01 00:04:23.8880,3721,31 St & Newtown Ave,40.767549,-73.920933,3592,Crescent St & Broadway,40.763359,-73.928647,39373,Subscriber,1974,1

In [8]:
april

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1437,2020-04-01 01:06:20.6300,2020-04-01 01:30:17.9680,3678,Fairmount Ave,40.725726,-74.071959,3678,Fairmount Ave,40.725726,-74.071959,42314,Customer,2002,2
1,264,2020-04-01 05:02:42.0570,2020-04-01 05:07:06.1260,3207,Oakland Ave,40.737604,-74.052478,3195,Sip Ave,40.730897,-74.063913,42146,Subscriber,1963,2
2,254,2020-04-01 06:20:28.1190,2020-04-01 06:24:42.1380,3678,Fairmount Ave,40.725726,-74.071959,3195,Sip Ave,40.730897,-74.063913,42255,Subscriber,1981,1
3,429,2020-04-01 06:33:30.5170,2020-04-01 06:40:40.1990,3195,Sip Ave,40.730897,-74.063913,3679,Bergen Ave,40.722104,-74.071455,42529,Subscriber,1964,1
4,805,2020-04-01 06:38:32.9220,2020-04-01 06:51:58.2050,3193,Lincoln Park,40.724605,-74.078406,3195,Sip Ave,40.730897,-74.063913,42362,Subscriber,1965,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9263,597,2020-04-30 22:18:40.4140,2020-04-30 22:28:38.1280,3678,Fairmount Ave,40.725726,-74.071959,3279,Dixon Mills,40.721630,-74.049968,42240,Customer,1969,0
9264,311,2020-04-30 22:23:18.7780,2020-04-30 22:28:30.2980,3195,Sip Ave,40.730897,-74.063913,3679,Bergen Ave,40.722104,-74.071455,42535,Subscriber,1986,1
9265,167,2020-04-30 22:34:51.8480,2020-04-30 22:37:39.6690,3640,Journal Square,40.733670,-74.062500,3206,Hilltop,40.731169,-74.057574,42615,Subscriber,1991,1
9266,520,2020-04-30 22:50:52.2380,2020-04-30 22:59:33.1620,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,42403,Subscriber,1976,1
9267,1043,2020-04-30 22:54:39.0840,2020-04-30 23:12:02.1790,3191,Union St,40.718211,-74.083639,3275,Columbus Drive,40.718355,-74.038914,42255,Customer,1999,1

In [9]:
may

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,336,2020-05-01 00:01:06.3380,2020-05-01 00:06:42.9560,2017,E 43 St & 2 Ave,40.750224,-73.971214,465,Broadway & W 41 St,40.755136,-73.986580,18015,Subscriber,1993,1
1,853,2020-05-01 00:01:08.1950,2020-05-01 00:15:21.2150,3376,E 65 St & 2 Ave,40.764719,-73.962221,478,11 Ave & W 41 St,40.760301,-73.998842,35905,Subscriber,1989,1
2,78,2020-05-01 00:01:08.5260,2020-05-01 00:02:27.0490,396,Lefferts Pl & Franklin Ave,40.680342,-73.955769,3789,Fulton St & Irving Pl,40.681860,-73.959432,33350,Subscriber,1938,2
3,1185,2020-05-01 00:02:22.4380,2020-05-01 00:22:08.1220,3630,Frederick Douglass Blvd & W 115 St,40.803865,-73.955931,3506,Lexington Ave & E 120 St,40.801307,-73.939817,43790,Subscriber,1996,1
4,272,2020-05-01 00:02:32.8280,2020-05-01 00:07:05.0880,3776,Central Ave & Starr Street,40.700003,-73.928340,3068,Humboldt St & Varet St,40.703172,-73.940636,39912,Subscriber,1993,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1487885,981,2020-05-31 23:59:19.0310,2020-06-01 00:15:40.5590,313,Washington Ave & Park Ave,40.696102,-73.967510,217,Old Fulton St,40.702772,-73.993836,43706,Subscriber,1972,2
1487886,367,2020-05-31 23:59:36.2270,2020-06-01 00:05:43.6200,545,E 23 St & 1 Ave,40.736502,-73.978095,501,FDR Drive & E 35 St,40.744219,-73.971212,41321,Subscriber,1994,2
1487887,1798,2020-05-31 23:59:37.7250,2020-06-01 00:29:36.6800,450,W 49 St & 8 Ave,40.762272,-73.987882,485,W 37 St & 5 Ave,40.750380,-73.983390,37418,Subscriber,1998,1
1487888,718,2020-05-31 23:59:47.7090,2020-06-01 00:11:46.5210,3691,28 Ave & 44 St,40.764089,-73.910651,3691,28 Ave & 44 St,40.764089,-73.910651,41190,Customer,1969,0
1487889,1168,2020-05-31 23:59:48.0660,2020-06-01 00:19:16.4730,467,Dean St & 4 Ave,40.683125,-73.978951,239,Willoughby St & Fleet St,40.691966,-73.981302,33450,Customer,2000,1

In [10]:
june

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1062,2020-06-01 00:00:03.3720,2020-06-01 00:17:46.2080,3419,Douglass St & 4 Ave,40.679279,-73.981540,3419,Douglass St & 4 Ave,40.679279,-73.981540,39852,Customer,1997,2
1,3810,2020-06-01 00:00:03.5530,2020-06-01 01:03:33.9360,366,Clinton Ave & Myrtle Ave,40.693261,-73.968896,336,Sullivan St & Washington Sq,40.730477,-73.999061,37558,Subscriber,1969,0
2,1017,2020-06-01 00:00:09.6140,2020-06-01 00:17:06.8330,389,Broadway & Berry St,40.710446,-73.965251,3562,Classon Ave & St Marks Ave,40.676520,-73.959608,37512,Customer,1988,2
3,226,2020-06-01 00:00:12.1780,2020-06-01 00:03:58.8640,3255,8 Ave & W 31 St,40.750585,-73.994685,505,6 Ave & W 33 St,40.749013,-73.988484,39674,Customer,1969,0
4,1437,2020-06-01 00:00:21.2550,2020-06-01 00:24:18.9650,367,E 53 St & Lexington Ave,40.758281,-73.970694,497,E 17 St & Broadway,40.737050,-73.990093,21093,Customer,1997,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1882268,685,2020-06-30 23:59:41.1160,2020-07-01 00:11:06.7790,503,E 20 St & Park Ave,40.738274,-73.987520,3746,6 Ave & Broome St,40.724308,-74.004730,21056,Customer,1993,2
1882269,446,2020-06-30 23:59:46.4260,2020-07-01 00:07:13.0860,3699,W 50 St & 9 Ave,40.763605,-73.989180,523,W 38 St & 8 Ave,40.754666,-73.991382,30164,Customer,1969,0
1882270,439,2020-06-30 23:59:47.4770,2020-07-01 00:07:06.5590,3699,W 50 St & 9 Ave,40.763605,-73.989180,523,W 38 St & 8 Ave,40.754666,-73.991382,43742,Customer,1986,1
1882271,890,2020-06-30 23:59:53.3950,2020-07-01 00:14:43.4270,3852,Stewart Ave & Johnson Ave,40.708690,-73.925870,3054,Greene Ave & Throop Ave,40.689493,-73.942061,15787,Subscriber,1994,1
1882272,433,2020-06-30 23:59:53.9010,2020-07-01 00:07:07.0950,324,DeKalb Ave & Hudson Ave,40.689888,-73.981013,261,Johnson St & Gold St,40.694749,-73.983625,38767,Customer,1990,1

In [11]:
july

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,341,2020-07-01 00:00:01.3020,2020-07-01 00:05:42.5650,3463,E 16 St & Irving Pl,40.735367,-73.987974,2003,1 Ave & E 18 St,40.733812,-73.980544,33861,Subscriber,1986,1
1,321,2020-07-01 00:00:01.3620,2020-07-01 00:05:22.9490,3463,E 16 St & Irving Pl,40.735367,-73.987974,2003,1 Ave & E 18 St,40.733812,-73.980544,31233,Subscriber,1990,2
2,2710,2020-07-01 00:00:06.6290,2020-07-01 00:45:17.3410,426,West St & Chambers St,40.717548,-74.013221,212,W 16 St & The High Line,40.743349,-74.006818,40329,Customer,1969,0
3,2685,2020-07-01 00:00:13.0220,2020-07-01 00:44:58.8640,426,West St & Chambers St,40.717548,-74.013221,212,W 16 St & The High Line,40.743349,-74.006818,17567,Subscriber,1998,1
4,191,2020-07-01 00:00:13.4660,2020-07-01 00:03:24.6230,3615,44 Dr & 21 St,40.748000,-73.946093,3127,9 St & 44 Rd,40.749660,-73.952100,43421,Subscriber,1992,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2105803,877,2020-07-31 23:59:48.9250,2020-08-01 00:14:26.2540,217,Old Fulton St,40.702772,-73.993836,398,Atlantic Ave & Furman St,40.691652,-73.999979,44073,Customer,1969,0
2105804,839,2020-07-31 23:59:51.7740,2020-08-01 00:13:50.9750,4044,8 Ave & W 38 St,40.754610,-73.991770,3163,Central Park West & W 68 St,40.773407,-73.977825,41797,Customer,2002,1
2105805,1042,2020-07-31 23:59:56.1460,2020-08-01 00:17:18.5090,3723,Cadman Plaza E & Johnson St,40.695317,-73.990157,350,Clinton St & Grand St,40.715595,-73.987030,24808,Subscriber,1974,1
2105806,699,2020-07-31 23:59:57.4310,2020-08-01 00:11:36.5420,161,LaGuardia Pl & W 3 St,40.729170,-73.998102,504,1 Ave & E 16 St,40.732219,-73.981656,41486,Subscriber,1991,1
2105807,249,2020-07-31 23:59:58.7260,2020-08-01 00:04:08.2070,446,W 24 St & 7 Ave,40.744876,-73.995299,3259,9 Ave & W 28 St,40.749370,-73.999234,28699,Customer,1990,1

In [12]:
august

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,561,2020-08-01 00:00:16.5960,2020-08-01 00:09:38.5610,3185,City Hall,40.717732,-74.043845,3185,City Hall,40.717732,-74.043845,42303,Customer,1994,2
1,236,2020-08-01 00:00:46.3900,2020-08-01 00:04:42.8890,3186,Grove St PATH,40.719586,-74.043117,3270,Jersey & 6th St,40.725289,-74.045572,44989,Subscriber,1996,1
2,384,2020-08-01 00:02:38.9250,2020-08-01 00:09:03.7590,3186,Grove St PATH,40.719586,-74.043117,3203,Hamilton Park,40.727596,-74.044247,41696,Subscriber,1984,2
3,1302,2020-08-01 00:03:27.0270,2020-08-01 00:25:09.2120,3185,City Hall,40.717732,-74.043845,3185,City Hall,40.717732,-74.043845,42310,Customer,1993,1
4,5561,2020-08-01 00:03:57.4810,2020-08-01 01:36:38.5000,3185,City Hall,40.717732,-74.043845,3185,City Hall,40.717732,-74.043845,42346,Customer,1995,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43262,162,2020-08-31 23:43:15.8540,2020-08-31 23:45:58.4550,3186,Grove St PATH,40.719586,-74.043117,3279,Dixon Mills,40.721630,-74.049968,44787,Subscriber,1977,1
43263,400,2020-08-31 23:46:19.9130,2020-08-31 23:53:00.3610,3481,York St,40.716490,-74.041050,3187,Warren St,40.721124,-74.038051,19153,Subscriber,1986,1
43264,288,2020-08-31 23:47:16.8680,2020-08-31 23:52:05.5550,3195,Sip Ave,40.730897,-74.063913,3194,McGinley Square,40.725340,-74.067622,42434,Subscriber,1960,1
43265,199,2020-08-31 23:50:37.2650,2020-08-31 23:53:56.9490,3195,Sip Ave,40.730897,-74.063913,3194,McGinley Square,40.725340,-74.067622,44226,Subscriber,1994,1
43266,333,2020-08-31 23:55:30.8050,2020-09-01 00:01:04.4110,3211,Newark Ave,40.721525,-74.046305,3270,Jersey & 6th St,40.725289,-74.045572,42437,Subscriber,1984,2

In [13]:
september

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,4225,2020-09-01 00:00:01.0430,2020-09-01 01:10:26.6350,3508,St Nicholas Ave & Manhattan Ave,40.809725,-73.953149,116,W 17 St & 8 Ave,40.741776,-74.001497,44317,Customer,1979,1
1,1868,2020-09-01 00:00:04.8320,2020-09-01 00:31:13.7650,3621,27 Ave & 9 St,40.773983,-73.930913,3094,Graham Ave & Withers St,40.716981,-73.944859,37793,Customer,1991,1
2,1097,2020-09-01 00:00:06.8990,2020-09-01 00:18:24.2260,3492,E 118 St & Park Ave,40.800539,-73.941995,3959,Edgecombe Ave & W 145 St,40.823498,-73.943860,41438,Subscriber,1984,1
3,1473,2020-09-01 00:00:07.7440,2020-09-01 00:24:41.1800,3946,St Nicholas Ave & W 137 St,40.818477,-73.947568,4002,W 144 St & Adam Clayton Powell Blvd,40.820877,-73.939249,35860,Customer,1990,2
4,1193,2020-09-01 00:00:12.2020,2020-09-01 00:20:05.5470,3081,Graham Ave & Grand St,40.711863,-73.944024,3048,Putnam Ave & Nostrand Ave,40.684020,-73.949770,26396,Customer,1969,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2488220,1818,2020-09-30 23:59:48.8460,2020-10-01 00:30:07.7810,284,Greenwich Ave & 8 Ave,40.739017,-74.002638,3836,Bushwick Ave & Linden St,40.691460,-73.921460,36220,Subscriber,1993,1
2488221,1553,2020-09-30 23:59:53.7240,2020-10-01 00:25:47.1760,390,Duffield St & Willoughby St,40.692216,-73.984284,3799,6 Ave & W 34 St,40.749640,-73.988050,31092,Subscriber,1995,1
2488222,626,2020-09-30 23:59:54.6670,2020-10-01 00:10:21.6050,3901,Stanhope St & Fairview Ave,40.709980,-73.911160,3083,Bushwick Ave & Powers St,40.712477,-73.941000,47224,Subscriber,1954,2
2488223,325,2020-09-30 23:59:56.2120,2020-10-01 00:05:21.3060,3148,E 84 St & 1 Ave,40.775655,-73.950686,3338,2 Ave & E 99 St,40.786259,-73.945526,16759,Subscriber,1995,2
2488224,128,2020-09-30 23:59:57.8350,2020-10-01 00:02:06.0920,439,E 4 St & 2 Ave,40.726281,-73.989780,312,Allen St & Stanton St,40.722055,-73.989111,47718,Subscriber,1996,2

In [14]:
october

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1403,2020-10-01 00:00:10.7870,2020-10-01 00:23:34.5400,224,Spruce St & Nassau St,40.711464,-74.005524,3347,Van Brunt St & Wolcott St,40.677343,-74.012751,39079,Subscriber,1995,1
1,462,2020-10-01 00:00:18.2390,2020-10-01 00:08:00.5710,3161,W 76 St & Columbus Ave,40.780184,-73.977285,3158,W 63 St & Broadway,40.771639,-73.982614,41267,Subscriber,1998,2
2,770,2020-10-01 00:00:21.3070,2020-10-01 00:13:12.0840,354,Emerson Pl & Myrtle Ave,40.693631,-73.962236,3761,Cedar St & Myrtle Ave,40.697842,-73.926241,47398,Customer,1996,1
3,233,2020-10-01 00:00:25.0080,2020-10-01 00:04:18.6410,3141,1 Ave & E 68 St,40.765005,-73.958185,464,E 56 St & 3 Ave,40.759345,-73.967597,36482,Subscriber,1993,1
4,126,2020-10-01 00:00:25.3100,2020-10-01 00:02:32.1330,335,Washington Pl & Broadway,40.729039,-73.994046,229,Great Jones St,40.727434,-73.993790,45319,Subscriber,1989,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2248864,1120,2020-10-31 23:59:48.4470,2020-11-01 00:18:29.3280,471,Grand St & Havemeyer St,40.712868,-73.956981,3764,Bushwick Ave & McKibbin St,40.705517,-73.939360,35356,Customer,1996,1
2248865,859,2020-10-31 23:59:49.3770,2020-11-01 00:14:09.1920,4005,St. Nicholas Terrace & Convent Ave,40.821294,-73.947868,3960,Hamilton Pl & W 140 St,40.822756,-73.951346,48322,Customer,1999,1
2248866,546,2020-10-31 23:59:52.1040,2020-11-01 00:08:59.0710,4010,W 145 St & Amsterdam Ave,40.825244,-73.947257,4057,Amsterdam Ave & W 167 St,40.839443,-73.937044,44589,Subscriber,1976,1
2248867,748,2020-10-31 23:59:53.0290,2020-11-01 00:12:21.7830,3783,Cliff St & Fulton St,40.708380,-74.004950,432,E 7 St & Avenue A,40.726218,-73.983799,48511,Subscriber,1997,2
2248868,1366,2020-10-31 23:59:57.9770,2020-11-01 00:22:44.1290,402,Broadway & E 22 St,40.740343,-73.989551,468,Broadway & W 56 St,40.765265,-73.981923,37248,Subscriber,1974,2

In [15]:
november

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,521,2020-11-01 00:00:07.0150,2020-11-01 00:08:48.3010,3467,W Broadway & Spring St,40.724947,-74.001659,350,Clinton St & Grand St,40.715595,-73.987030,40405,Subscriber,1989,1
1,492,2020-11-01 00:00:10.8080,2020-11-01 00:08:23.3170,3557,40 Ave & 9 St,40.757420,-73.945133,3557,40 Ave & 9 St,40.757420,-73.945133,46504,Subscriber,1970,2
2,1979,2020-11-01 00:00:14.7040,2020-11-01 00:33:14.1640,3085,Roebling St & N 4 St,40.714690,-73.957390,3854,Morgan Ave & Maspeth Ave,40.716657,-73.936370,37452,Subscriber,1989,2
3,2382,2020-11-01 00:00:14.7070,2020-11-01 00:39:57.0030,3783,Cliff St & Fulton St,40.708380,-74.004950,3167,Amsterdam Ave & W 73 St,40.779668,-73.980930,40417,Subscriber,1981,1
4,166,2020-11-01 00:00:15.9690,2020-11-01 00:03:02.8980,422,W 59 St & 10 Ave,40.770513,-73.988038,3175,W 70 St & Amsterdam Ave,40.777480,-73.982886,35776,Subscriber,1990,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1736699,257,2020-11-30 23:58:44.6840,2020-12-01 00:03:01.9470,324,DeKalb Ave & Hudson Ave,40.689888,-73.981013,421,Clermont Ave & Park Ave,40.695734,-73.971297,49932,Subscriber,1992,1
1736700,617,2020-11-30 23:58:45.6210,2020-12-01 00:09:02.8300,439,E 4 St & 2 Ave,40.726281,-73.989780,3709,W 15 St & 6 Ave,40.738046,-73.996430,38817,Customer,1969,0
1736701,116,2020-11-30 23:58:45.7200,2020-12-01 00:00:41.9570,3616,Steinway St & 28 Ave,40.765625,-73.913669,3600,31 Ave & Steinway St,40.761149,-73.917007,32874,Subscriber,1980,1
1736702,409,2020-11-30 23:59:20.1480,2020-12-01 00:06:09.7540,3521,Lenox Ave & W 111 St,40.798786,-73.952300,3325,E 95 St & 3 Ave,40.784903,-73.950503,36675,Customer,2001,1
1736703,301,2020-11-30 23:59:47.9750,2020-12-01 00:04:49.2260,241,DeKalb Ave & S Portland Ave,40.689810,-73.974931,274,Lafayette Ave & Fort Greene Pl,40.686919,-73.976682,27784,Subscriber,1948,1

In [16]:
december

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,146,2020-12-01 00:02:50.1450,2020-12-01 00:05:16.1940,3202,Newport PATH,40.727224,-74.033759,3199,Newport Pkwy,40.728745,-74.032108,42308,Subscriber,1989,2
1,572,2020-12-01 00:11:57.3910,2020-12-01 00:21:30.2510,3640,Journal Square,40.733670,-74.062500,3280,Astor Place,40.719282,-74.071262,18568,Subscriber,1997,2
2,387,2020-12-01 00:14:49.3610,2020-12-01 00:21:16.8730,3640,Journal Square,40.733670,-74.062500,3194,McGinley Square,40.725340,-74.067622,44543,Subscriber,1960,1
3,188,2020-12-01 00:45:06.3680,2020-12-01 00:48:14.4280,3186,Grove St PATH,40.719586,-74.043117,3270,Jersey & 6th St,40.725289,-74.045572,43098,Subscriber,1998,1
4,594,2020-12-01 01:17:17.0110,2020-12-01 01:27:11.9400,3212,Christ Hospital,40.734786,-74.050444,3209,Brunswick St,40.724176,-74.050656,44723,Subscriber,1988,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11689,1750,2020-12-31 23:07:44.0030,2020-12-31 23:36:54.4710,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,40440,Customer,1969,0
11690,1519,2020-12-31 23:18:00.2630,2020-12-31 23:43:19.8590,3184,Paulus Hook,40.714145,-74.033552,3195,Sip Ave,40.730897,-74.063913,46340,Customer,1969,0
11691,1761,2020-12-31 23:31:09.4620,2021-01-01 00:00:31.3290,3195,Sip Ave,40.730897,-74.063913,3270,Jersey & 6th St,40.725289,-74.045572,40907,Customer,1998,1
11692,637,2020-12-31 23:35:45.4640,2020-12-31 23:46:22.7300,3681,Grand St,40.715178,-74.037683,3199,Newport Pkwy,40.728745,-74.032108,42250,Customer,1969,0
11693,1607,2020-12-31 23:48:34.5750,2021-01-01 00:15:22.3090,3267,Morris Canal,40.712419,-74.038526,3267,Morris Canal,40.712419,-74.038526,48742,Subscriber,1982,1

In [17]:
#merging the tabels
frames = [january, february, march, april, may, june, july, august, september, october, november, december]

In [36]:
entire_twenty_twenty = pd.concat(frames)

In [39]:
entire_twenty_twenty

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,226,2020-01-01 00:04:50.1920,2020-01-01 00:08:37.0370,3186,Grove St PATH,40.719586,-74.043117,3211,Newark Ave,40.721525,-74.046305,29444,Subscriber,1984,2
1,377,2020-01-01 00:16:01.6700,2020-01-01 00:22:19.0800,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,26305,Subscriber,1989,2
2,288,2020-01-01 00:17:33.8770,2020-01-01 00:22:22.4420,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,29268,Customer,1989,1
3,435,2020-01-01 00:32:05.9020,2020-01-01 00:39:21.0660,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,29278,Customer,1969,0
4,231,2020-01-01 00:46:19.6780,2020-01-01 00:50:11.3440,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,-74.042817,29276,Subscriber,1983,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11689,1750,2020-12-31 23:07:44.0030,2020-12-31 23:36:54.4710,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,40440,Customer,1969,0
11690,1519,2020-12-31 23:18:00.2630,2020-12-31 23:43:19.8590,3184,Paulus Hook,40.714145,-74.033552,3195,Sip Ave,40.730897,-74.063913,46340,Customer,1969,0
11691,1761,2020-12-31 23:31:09.4620,2021-01-01 00:00:31.3290,3195,Sip Ave,40.730897,-74.063913,3270,Jersey & 6th St,40.725289,-74.045572,40907,Customer,1998,1
11692,637,2020-12-31 23:35:45.4640,2020-12-31 23:46:22.7300,3681,Grand St,40.715178,-74.037683,3199,Newport Pkwy,40.728745,-74.032108,42250,Customer,1969,0
11693,1607,2020-12-31 23:48:34.5750,2021-01-01 00:15:22.3090,3267,Morris Canal,40.712419,-74.038526,3267,Morris Canal,40.712419,-74.038526,48742,Subscriber,1982,1

In [40]:
entire_twenty_twenty.count()

tripduration               14255305
starttime                  14255305
stoptime                   14255305
start station id           14255305
start station name         14255305
start station latitude     14255305
start station longitude    14255305
end station id             14255305
end station name           14255305
end station latitude       14255305
end station longitude      14255305
bikeid                     14255305
usertype                   14255305
birth year                 14255305
gender                     14255305
dtype: int64

In [46]:
entire_twenty_twenty.to_csv("Trip History 2020 data.csv")

In [47]:
 trip_data = os.path.join("Trip History 2020 data.csv" )
 trip_history_data_2020 = pd.read_csv(trip_data)

In [48]:
trip_history_data_2020

,Unnamed: 0,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,0,226,2020-01-01 00:04:50.1920,2020-01-01 00:08:37.0370,3186,Grove St PATH,40.719586,-74.043117,3211,Newark Ave,40.721525,-74.046305,29444,Subscriber,1984,2
1,1,377,2020-01-01 00:16:01.6700,2020-01-01 00:22:19.0800,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,26305,Subscriber,1989,2
2,2,288,2020-01-01 00:17:33.8770,2020-01-01 00:22:22.4420,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,29268,Customer,1989,1
3,3,435,2020-01-01 00:32:05.9020,2020-01-01 00:39:21.0660,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,29278,Customer,1969,0
4,4,231,2020-01-01 00:46:19.6780,2020-01-01 00:50:11.3440,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,-74.042817,29276,Subscriber,1983,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14255300,11689,1750,2020-12-31 23:07:44.0030,2020-12-31 23:36:54.4710,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,40440,Customer,1969,0
14255301,11690,1519,2020-12-31 23:18:00.2630,2020-12-31 23:43:19.8590,3184,Paulus Hook,40.714145,-74.033552,3195,Sip Ave,40.730897,-74.063913,46340,Customer,1969,0
14255302,11691,1761,2020-12-31 23:31:09.4620,2021-01-01 00:00:31.3290,3195,Sip Ave,40.730897,-74.063913,3270,Jersey & 6th St,40.725289,-74.045572,40907,Customer,1998,1
14255303,11692,637,2020-12-31 23:35:45.4640,2020-12-31 23:46:22.7300,3681,Grand St,40.715178,-74.037683,3199,Newport Pkwy,40.728745,-74.032108,42250,Customer,1969,0
14255304,11693,1607,2020-12-31 23:48:34.5750,2021-01-01 00:15:22.3090,3267,Morris Canal,40.712419,-74.038526,3267,Morris Canal,40.712419,-74.038526,48742,Subscriber,1982,1

In [49]:
trip_history_data_2020.count()

Unnamed: 0                 14255305
tripduration               14255305
starttime                  14255305
stoptime                   14255305
start station id           14255305
start station name         14255305
start station latitude     14255305
start station longitude    14255305
end station id             14255305
end station name           14255305
end station latitude       14255305
end station longitude      14255305
bikeid                     14255305
usertype                   14255305
birth year                 14255305
gender                     14255305
dtype: int64